[application]
name = "basedradio-app"

[bundle]
identifier = "radio.based.desktop"
publisher = "Rpgwaiter"
icon = ["assets/icons/favicon-32x32521f.png"]

[web.app]
# HTML title tag content (overwritten by code)
title = "BasedRadio"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

